services:
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=3y'
      - '--web.enable-lifecycle'

  json_exporter:
    image: prometheuscommunity/json-exporter:latest
    restart: unless-stopped
    ports:
      - 7979:7979
    volumes:
      - ./json_exporter.yml:/config.yml:ro
    command:
      - '--config.file=/config.yml'
